import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const supabaseUrl = Deno.env.get("SUPABASE_URL") ?? ""; const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""; const workerSecret = Deno.env.get("NOTION_WORKER_SECRET") ?? ""; const notionToken = Deno.env.get("NOTION_TOKEN") ?? ""; const sessionsSource = Deno.env.get("NOTION_WORKOUT_SESSIONS_DATA_SOURCE_ID") ?? ""; const logsSource = Deno.env.get("NOTION_EXERCISE_LOGS_DATA_SOURCE_ID") ?? ""; const batchSize = Math.max(1, Math.min(Number(Deno.env.get("NOTION_WORKER_BATCH_SIZE") ?? 10) || 10, 100));
const nh = { Authorization: `Bearer ${notionToken}`, "Notion-Version": "2025-09-03", "Content-Type": "application/json" };
function json(body: unknown, status = 200) { return new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json" } }); } function title(v: string) { return { title: [{ type: "text", text: { content: v.slice(0, 2000) } }] }; } function rich(v: string) { return v ? { rich_text: [{ type: "text", text: { content: v.slice(0, 2000) } }] } : { rich_text: [] }; } function number(v: unknown) { const text = String(v ?? "").trim(); if (!text) return null; const n = Number(text); return Number.isFinite(n) ? n : null; }
async function notion(path: string, init: RequestInit = {}) { const r = await fetch(`https://api.notion.com/v1${path}`, { ...init, headers: { ...nh, ...(init.headers ?? {}) } }); if (!r.ok) throw new Error(`Notion request failed (${r.status})`); return r.json(); }
async function find(source: string, property: string, value: string) { const result = await notion(`/data_sources/${source}/query`, { method: "POST", body: JSON.stringify({ filter: { property, rich_text: { equals: value } }, page_size: 1 }) }); return result.results?.[0] ?? null; }
async function create(source: string, properties: Record<string, unknown>) { return notion("/pages", { method: "POST", body: JSON.stringify({ parent: { data_source_id: source }, properties }) }); }
Deno.serve(async (request) => { if (request.method !== "POST") return json({ error: "POST required" }, 405); if (!workerSecret || !supabaseUrl || !serviceRoleKey || !notionToken || !sessionsSource || !logsSource) return json({ error: "Worker is not configured" }, 503); if (request.headers.get("Authorization") !== `Bearer ${workerSecret}`) return json({ error: "Unauthorized" }, 401); const admin = createClient(supabaseUrl, serviceRoleKey); const { data: sessions, error: claimError } = await admin.rpc("claim_lifting_notion_sessions", { p_limit: batchSize }); if (claimError) return json({ error: claimError.message }, 500); const results: any[] = [];
  for (const session of sessions ?? []) { try { const { data: logs, error: logsError } = await admin.from("exercise_logs").select("*").eq("session_id", session.id).order("exercise_id").order("set_number"); if (logsError) throw logsError; let sessionPage = session.notion_page_id ? { id: session.notion_page_id } : await find(sessionsSource, "Supabase Session ID", session.id); if (!sessionPage) { const summary = (logs ?? []).map((l: any) => `${l.exercise_name}: ${l.reps || "—"} reps @ ${l.weight || "—"}`).join("\n"); sessionPage = await create(sessionsSource, { Session: title(`${session.routine_name} — ${session.workout_date}`), "Completed At": { date: { start: session.finished_at } }, Routine: { select: { name: session.routine_name } }, "Supabase Session ID": rich(session.id), "Started At": { date: { start: session.started_at } }, Notes: rich(summary) }); } for (const log of logs ?? []) { const setId = log.id; let page = log.notion_page_id ? { id: log.notion_page_id } : await find(logsSource, "Supabase Set ID", setId); if (!page) { const props: Record<string, unknown> = { Exercise: title(log.exercise_name), "Workout Session": { relation: [{ id: sessionPage.id }] }, Set: { number: log.set_number }, Weight: rich(log.weight ?? ""), Completed: { checkbox: Boolean(log.completed) }, Routine: { select: { name: session.routine_name } }, "Supabase Set ID": rich(setId) }; const reps = number(log.reps); if (reps !== null) props.Reps = { number: reps }; page = await create(logsSource, props); } const { error } = await admin.from("exercise_logs").update({ notion_page_id: page.id }).eq("id", log.id); if (error) throw error; } const { error: completeError } = await admin.rpc("complete_lifting_notion_session", { p_session_id: session.id, p_page_id: sessionPage.id }); if (completeError) throw completeError; results.push({ sessionId: session.id, status: "synced" }); } catch (error) { const message = error instanceof Error ? error.message : "Unknown worker error"; await admin.rpc("fail_lifting_notion_session", { p_session_id: session.id, p_error: message, p_delay: "00:05:00" }); results.push({ sessionId: session.id, status: "failed", error: message }); } } return json({ ok: true, processed: results.length, results }); });
